config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :update, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
  	validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { maximum: 20 }
  validates :name, length: { minimum: 2 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!

	def index
		@books = Book.all
		@book_new = Book.new
	end

	def show
		@book_new = Book.new
		@book = Book.find(params[:id])
	end

	  def create
			@book_new = Book.new(book_params)
			@book_new.user_id = current_user.id
		    if @book_new.save
		      flash[:notice] = "Book was successfully created."
		      redirect_to book_path(@book_new)
		    else
		      @books = Book.all
        	  render :index
		    end
	  end

	def edit
		@book = Book.find(params[:id])
			if @book.user != current_user
				redirect_to books_path
			end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	  def update
  		@book = Book.find(params[:id])
	  	if @book.update(book_params)
	        flash[:notice] = "You have updated book successfully."
	    	redirect_to book_path(@book.id)
	      else
	        render :edit
	      end
  	  end

	  private
	    def book_params
	        params.require(:book).permit(:title, :body)
	    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def top
		if user_signed_in?
			redirect_to user_path(current_user.id)
		end
	end

	def about
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
		@book_new = Book.new
		@user = User.find(params[:id])
		@books = @user.books
  end

  def create
		@book = Book.new(book_params)
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to books_path
      end
  end

  def edit
  		@user = User.find(params[:id])
        if @user != current_user
        redirect_to user_path(current_user.id)
        end
  end

  def update
  		@user = User.find(params[:id])
  		# if @user.update(user_params)
      #   flash[:notice] = "User information was successfully updated."
    		# redirect_to user_path(@user.id)
      # else
      #   flash[:notice] = "information shall be within 50 letters."
      #   redirect_to edit_user_path(@user.id)
      # end

      if @user.update(user_params)
          flash[:notice] = "User information was successfully updated."
          redirect_to user_path(@user.id)
      else
            render :edit
      end
  end

  def index
      @book_new = Book.new
      @users = User.all
  end

  private
    def book_params
        params.require(:book).permit(:title, :body)
    end

    def user_params
    	params.require(:user).permit(:name, :profile_image, :introduction)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<section class="height_modification">

<% if @book.errors.any? %>
    <div class="error_explanation1">
    <%= @book.errors.count %> errors happened.
    </div>
    <div class="error_explanation2">
    <% @book.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
    </div>
<% end %>
	
	<div class="editing_box">
    <h2>Editing Book</h2>

        <%= form_for(@book) do |f| %>
          <div class="field">
            <label for="book_title">Title</label><br />
            <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-12" %>
          </div>
          <div class="field">
            <label for="book_title">Opinion</label><br />
            <%= f.text_field :body, autofocus: true, autocomplete: "body", class: "col-xs-12" %>
          </div>
          <div class="actions">
            <%= f.submit "Update Book", class: "btn btn-primary col-xs-12 actions" %>
          </div>
        <% end %>
    </div>

</section>

app/views/books/index.html.erb
<section class="height_modification">

<% if @book_new.errors.any? %>
    <div class="error_explanation1">
    <%= @book_new.errors.count %> errors happened.
    </div>
    <div class="error_explanation2">
    <% @book_new.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
    </div>
<% end %>

<div class="row">

  <div class="col-xs-3">

    <h2>User info</h2>
    <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, class: "pull-left profile-thumb margin_image", fallback: "no_image.jpg" %>

    <table class="table">
      <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
      </tbody>
    </table>

    <div class="botton">
      <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>

    <section class="height_modification">
    <h2>New book</h2>
    </section>

        <%= form_for(@book_new) do |f| %>
          <div class="field">
            <label for="book_title">Title</label><br />
            <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-12" %>
          </div>
          <div class="field">
            <label for="book_title">Opinion</label><br />
            <%= f.text_field :body, autofocus: true, autocomplete: "body", class: "col-xs-12" %>
          </div>
          <div class="actions">
            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12 actions" %>
          </div>
        <% end %>

  </div>

  <div class="col-xs-9">
    <h2>Books</h2>

    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
		      <th></th>
		      <th>Title</th>
		      <th>Opinion</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		  <tbody>
          <% @books.each do |book| %>
		      <tr>
		        <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "pull-left profile-thumb margin_icon", fallback: 'no_image.jpg', size: "40x40" %>
              <% end %>
            </td>
		        <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
		        <td>
              <%= book.body %>
            </td>
		      </tr>
          <% end %>
		  </tbody>
	</table>
  </div>

</div>
</section>

app/views/books/show.html.erb
<section class="height_modification">

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div class="row">
	<div class="col-xs-3">

    <h2>User info</h2>
    <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, class: "pull-left profile-thumb margin_image", fallback: "no_image.jpg" %>

    <table class="table">
      <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= @book.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @book.user.introduction %></th>
      </tr>
      </tbody>
    </table>

    <div class="botton">
      <% if @book.user == current_user %>
        <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
      <% else %>
        <%= link_to "", user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
      <% end %>
    </div>

    <section class="height_modification">
    <h2>New book</h2>
    </section>

        <%= form_for(@book_new) do |f| %>
          <div class="field">
            <label for="book_title">Title</label><br />
            <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-12" %>
          </div>
          <div class="field">
            <label for="book_title">Opinion</label><br />
            <%= f.text_field :body, autofocus: true, autocomplete: "body", class: "col-xs-12" %>
          </div>
          <div class="actions">
            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12 actions" %>
          </div>
        <% end %>
  	</div>

  	<div class="col-xs-9">
    <h2>Book Detail</h2>

    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
		      <th></th>
		      <th>Title</th>
		      <th>Opinion</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		  <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, class: "pull-left profile-thumb margin_icon", fallback: "no_image.jpg", size: "40x40" %>
              <div class="clearfix"></div>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              	<%= @book.title %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-success btm-sm" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: '削除しますか？' }, class: "btn btn-danger btm-sm" %>
              <% end %>
            </td>
          </tr>
		  </tbody>
	</table>
  	</div>


</div>
</section>

app/views/home/about.html.erb
<section class="height_modification">

	<div>
		<h1>
			Welcome to
			<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>
			!
		</h1>
	</div>

</section>

app/views/home/top.html.erb
<div class="body">
<div class="body-container">
	<div class="top-message col-md-offset-3 col-md-6">
    	<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><a class="btn btn-info col-xs-8 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-8 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>

  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class="container">
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <header>

        <header class="navbar navbar-fixed-top navbar-inverse">
          <div class="container">
            <nav class="nav navbar-nav navbar-left">
              <span>Bookers</span>
            </nav>
            <nav>
              <% if user_signed_in? %>
                  <ul class="nav navbar-nav navbar-right">
                      <li><a class="glyphicon glyphicon-home home" href="/">
                          Home
                      </a></li>
                      <li>
                        <%= link_to "  Users", users_path, class:"glyphicon glyphicon-user users" %>
                      </li>
                      <li><a class="glyphicon glyphicon-book books" href="/books">
                          Books
                      </a></li>
                      <li><a class="glyphicon glyphicon-log-out logout" rel="nofollow" data-method="delete" href="/users/sign_out">
                          logout
                      </a></li>
                  </ul>
              <% else %>
                  <ul class="nav navbar-nav navbar-right">
                      <li><a class="glyphicon glyphicon-home home" href="/">
                          Home
                      </a></li>
                      <li>
                          <%= link_to "  About", home_about_path, class:"glyphicon glyphicon-link about" %>
                      </li>
                      <li><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up">
                          sign up
                      </a></li>
                      <li><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in">
                          login
                      </a></li>
                  </ul>
              <% end %>
            </nav>
          </div>

        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>

        </header>

        

    <%= yield %>
  </body>
  <footer>
    <div class="footer_moji">
    CopyRight Infratop.inc
    </div>
  </footer>
</html>

app/views/users/edit.html.erb
<session class="new_register">

<% if @user.errors.any? %>
    <div class="error_explanation1">
    <%= @user.errors.count %> errors happened.
    </div>
    <div class="error_explanation2">
    <% @user.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
    </div>
<% end %>

<% if flash[:notice] %>
  <p class="notice2">1 error prohibited this obj from being saved:</p>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<div>
<h2>User Info</h2>

<%= form_for(@user) do |f| %>

    <div class="field clearfix">
        <label class="label_edit" for="user_name">Name</label>
        <span class="text_field">
        <%= f.text_field :name, autofocus: true, id:"user_name", placeholder:"名前"%>
        </span>
    </div>
    <div class="field clearfix">
        <label for="user_name">Image</label>
        <div class="user-edit-image">
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
        </div>
    </div>
    <div>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", id:"user_name", class: "user-edit-form" %>
    </div>
    <div class="field clearfix">
        <label class="label_edit2" for="user_name">Introduction</label>
        <span>
        <%= f.text_area :introduction, autofocus: true, id:"user_name", placeholder:"紹介文" %>
        </span>
    </div>
    <div class="field">
        <span class="text_field">
        <%= f.submit "Update User"%>
        </span>
    </div>

<% end %>

</div>
</session>

app/views/users/index.html.erb
<session class="height_modification">

<div class="row">
	<div class="col-xs-3">
	    <h2>User info</h2>
	    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "pull-left profile-thumb margin_image", fallback: "no_image.jpg" %>

	    <table class="table">
	      <tbody><tr></tr>
	      <tr>
	        <th>name</th>
	        <th><%= current_user.name %></th>
	      </tr>
	      <tr>
	        <th>introduction</th>
	        <th><%= current_user.introduction %></th>
	      </tr>
	      </tbody>
	    </table>

	    <div>
	      <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5575" %>
	    </div>

	    <section class="height_modification">
	    <h2>New book</h2>
	    </section>

	        <%= form_for(@book_new) do |f| %>
	          <div class="field3">
	            <label for="book_title">Title</label><br />
	            <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-12" %>
	          </div>
	          <div class="field3">
	            <label for="book_title">Opinion</label><br />
	            <%= f.text_field :body, autofocus: true, autocomplete: "body", class: "col-xs-12" %>
	          </div>
	          <div class="actions">
	            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12 actions" %>
	          </div>
	        <% end %>
	 </div>

	<div class="col-xs-9">
    <h2>Books</h2>

    <table class="table table-hover table-inverse">
		  <thead>
		    <tr>
		      <th>Image</th>
		      <th>Name</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		  <tbody>
          <% @users.each do |user| %>
		      <tr>
		        <td>
	              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, class: "pull-left profile-thumb margin_icon", fallback: 'no_image.jpg', size: "40x40" %>
            	</td>
		        <td>
              	<%= user.name %>
            	</td>
		        <td>
              	<%= link_to 'show', user_path(user) %>
            	</td>
		      </tr>
          <% end %>
		  </tbody>
	</table>
  </div>

</div>
</session>

app/views/users/show.html.erb
<div class="container">
<session class="height_modification">



<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
  
<div class="row">

  <div class="col-xs-3">

    <h2>User info</h2>
    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "pull-left profile-thumb margin_image", fallback: "no_image.jpg" %>

    <table class="table">
      <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
      </tbody>
    </table>

    <div>
      <% if @user == current_user %>
      <%= link_to "", edit_user_path(@user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5575" %>
      <% else %>
      <%= link_to "", user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5575" %>
      <% end %>
    </div>

    <section class="height_modification">
    <h2>New book</h2>
    </section>

        <%= form_for(@book_new) do |f| %>
          <div class="field3">
            <label for="book_title">Title</label><br />
            <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-12" %>
          </div>
          <div class="field3">
            <label for="book_title">Opinion</label><br />
            <%= f.text_field :body, autofocus: true, autocomplete: "body", class: "col-xs-12" %>
          </div>
          <div class="actions">
            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12 actions" %>
          </div>
        <% end %>

  </div>

  <div class="col-xs-9">
    <h2>Books</h2>

    <table class="table table-hover table-inverse">
		  <thead>
		    <tr> 
		      <th></th>
		      <th>Title</th>
		      <th>Opinion</th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		  <tbody>
		      <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, class: "pull-left profile-thumb margin_icon", fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
		  </tbody>
	</table>
  </div>

</div>
</session>
</div>